### ISSUE TITLE
可以正常搜索，但是无法打开工程，cmd+1或者回车都不生效

### ISSUE THREAD

**Issue by ideago** [mohuishou/utools#1]
目前发现两个问题哈

- 1.可以正常搜索，但是无法打开工程，cmd+1或者回车都不生效，我的环境如下

MacOS 10.14.6 

版本: 1.40.1
提交: 8795a9889db74563ddd43eb0a897a2384129a619
日期: 2019-11-13T16:47:44.719Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

- 2.搜索没有做大小写模糊，比如我搜索Note，必须得键入Note 不能识别 note

**Comment by mohuishou** [comment]
可以在终端使用code命令打开文件夹么？

**Comment by mohuishou** [comment]
已修复

**Comment by ideago** [comment]
确实已经解决了，非常棒……👍
