### ISSUE TITLE
vscode插件无法打开文件夹

### ISSUE THREAD

**Issue by yanyongyu** [mohuishou/utools#10]
插件版本：1.4.2

系统：Ubuntu18.04

Code: 1.42.1

使用命令vsc并且选择文件夹项目后，打开的是一个新的文件而非文件夹

**Comment by yanyongyu** [comment]
查看了一下区别，问题是插件获取的路径少了前缀/

示例：

> 实际路径：/media/yan/Data/project
> 插件显示路径：media/yan/Data/project

code实际打开路径：~/media/yan/Data/project

**Comment by mohuishou** [comment]
麻烦看一下 `storage.json` 文件里面路径

**Comment by yanyongyu** [comment]
> 麻烦看一下 `storage.json` 文件里面路径

嗯 我有看过，问题出在代码18行正则替换

示例文件路径

**file:///media/yan/Data/project**

**Comment by mohuishou** [comment]
好的，晚点修复一下

**Comment by mohuishou** [comment]
> > 麻烦看一下 `storage.json` 文件里面路径
> 
> 嗯 我有看过，问题出在代码28行正则替换
> 
> 示例文件路径
> 
> **file:///media/yan/Data/project**
> 
> `storage.json` 文件中所有路径都是这个样子的绝对路径

已修复 https://github.com/mohuishou/utools/releases/tag/v1.5.0

**Comment by yanyongyu** [comment]
> 已修复 https://github.com/mohuishou/utools/releases/tag/v1.5.0

非常感谢！这个插件方便快捷很好用！

**Comment by yanyongyu** [comment]
> 已修复 https://github.com/mohuishou/utools/releases/tag/v1.5.0

vscode v1.5.0安装时出现preload文件不存在。是不是打包出了点问题:joy:

**Comment by mohuishou** [comment]
> > 已修复 https://github.com/mohuishou/utools/releases/tag/v1.5.0
> 
> vscode v1.5.0安装时出现preload文件不存在。是不是打包出了点问题😂

已经发布到插件中心了，可以直接在插件中心安装，github上可能是自动打包出了点问题

**Comment by mohuishou** [comment]
github 上的也修复了， https://github.com/mohuishou/utools/releases/tag/v1.5.1
