### ISSUE TITLE
打包后启动报错

### ISSUE THREAD

**Issue by whx159** [mohuishou/utools#106]
![image](https://github.com/mohuishou/utools/assets/30753601/14203068-c8c8-47d0-bb2f-7f75947f1bae)

`try {
    const utools_helper_1 = require("utools-helper");
} catch (error) {
    alert(error)
}`

报错：Error: ENOENT, node_modules/.store/utools-helper@2.1.0/node_modules/utools-helper not found in /Users/xxx/Library/Application Support/uTools/plugins/unsafe-28fc55708b016a64ca5fbdabd347ccef.asar

node_modules中有utools-helper。

**Comment by mohuishou** [comment]
应该是你打包的时候没把 node_modules 打包进去

**Comment by whx159** [comment]
打包选择的是整个目录（test1），并且解压unsafe-28fc55708b016a64ca5fbdabd347ccef.asar之后也是有node_modules的。
目录如下：
![image](https://github.com/mohuishou/utools/assets/30753601/d543addf-8d15-4534-a228-720d1a4f5cbd)
打包路径：
![image](https://github.com/mohuishou/utools/assets/30753601/7b62b4f4-d46c-48e7-b059-007e452ae02e)

**Comment by whx159** [comment]
不打包使用时没有问题的

**Comment by mohuishou** [comment]
那就是打包的问题哈，可以看看目录结构什么的有没有问题

**Comment by whx159** [comment]
![image](https://github.com/mohuishou/utools/assets/30753601/52f02ae5-0c61-42a2-ab59-565878d57841)
yuque这个项目打包后也报一样的错，应该怎么打包啊

**Comment by whx159** [comment]
![image](https://github.com/mohuishou/utools/assets/30753601/62fd891d-40b9-45ca-a60e-a994973bad14)
yuque这项目打包后也是报错的。应该怎么打包呢

**Comment by mohuishou** [comment]
plugin.json 文件和 node_modules 是同目录么？同目录理论上没问题，这个项目很久没改过了不知道是不是 utools 那边有什么修改导致不行了

**Comment by whx159** [comment]
现在你自己打包这个项目可以运行吗，方便试一下吗。你也不行的话，我就不纠结了。

**Comment by mohuishou** [comment]
我试了一下，离线打包之后跑不起来了，感觉可能是 utools 的问题，直接开始运行是可以的，不过我没你那个报错
