### ISSUE TITLE
Bug: 貌似在 win11 里无法使用 vscode 插件

### ISSUE THREAD

**Issue by huankong233** [mohuishou/utools#108]
![image](https://github.com/user-attachments/assets/b1bb0933-09e1-4e77-8bd3-963307bae769)

之前老电脑上运行的好好的

信息
版本: 1.92.2 (user setup)
提交: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
日期: 2024-08-14T17:29:30.058Z
Electron: 30.1.2
ElectronBuildId: 9870757
Chromium: 124.0.6367.243
Node.js: 20.14.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.22631

win11 23h2

**Comment by mohuishou** [comment]
有什么报错么，我在 win11 上用没有问题
--------------原始邮件--------------
发件人："huan_kong ***@***.***&gt;;
发送时间：2024年9月1日(星期天) 下午2:45
收件人："mohuishou/utools" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[mohuishou/utools] Bug: 貌似在 win11 里无法使用 vscode 插件 (Issue #108)
-----------------------------------

 

 
image.png (view on web)
 
之前老电脑上运行的好好的
 
信息
 版本: 1.92.2 (user setup)
 提交: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9
 日期: 2024-08-14T17:29:30.058Z
 Electron: 30.1.2
 ElectronBuildId: 9870757
 Chromium: 124.0.6367.243
 Node.js: 20.14.0
 V8: 12.4.254.20-electron.0
 OS: Windows_NT x64 10.0.22631
 
win11 23h2

**Comment by huankong233** [comment]
> 有什么报错么，我在 win11 上用没有问题 --------------原始邮件-------------- 发件人："huan_kong ***@***.***&gt;; 发送时间：2024年9月1日(星期天) 下午2:45 收件人："mohuishou/utools" ***@***.***&gt;; 抄送："Subscribed ***@***.***&gt;; 主题：[mohuishou/utools] Bug: 貌似在 win11 里无法使用 vscode 插件 (Issue #108) ----------------------------------- image.png (view on web) 之前老电脑上运行的好好的 信息 版本: 1.92.2 (user setup) 提交: fee1edb8d6d72a0ddff41e5f71a671c23ed924b9 日期: 2024-08-14T17:29:30.058Z Electron: 30.1.2 ElectronBuildId: 9870757 Chromium: 124.0.6367.243 Node.js: 20.14.0 V8: 12.4.254.20-electron.0 OS: Windows_NT x64 10.0.22631 win11 23h2 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

哪里可以看报错，打开界面只有一个显示了 `Error: Invalid rev format` 运行 `vsc-settings` 也一样提示这个

**Comment by mohuishou** [comment]
- 可以尝试清除插件数据试一下
- 可以尝试终端执行一下 code 命令试一下

**Comment by huankong233** [comment]
> * 可以尝试清除插件数据试一下
> * 可以尝试终端执行一下 code 命令试一下

重装过插件了，貌似不行，终端执行 `code` 可以正常打开 `vscode`

![image](https://github.com/user-attachments/assets/59bc06f8-1c63-4256-bae0-20ebb67e2488)

**Comment by mohuishou** [comment]
重装不行，重装数据应该还是在的，得手动清除一下插件数据

**Comment by huankong233** [comment]
> 重装不行，重装数据应该还是在的，得手动清除一下插件数据

emmm在哪里清除，翻了一下没找到，就看到了这个

![image](https://github.com/user-attachments/assets/a74b4a4c-4e55-4ee1-8180-15b4e106b909)

**Comment by mohuishou** [comment]
是这里，没有对应插件就是没有数据了，那有点奇怪了，不清楚和 utools 升级有没有关系，后面看下能不能复现吧

**Comment by huankong233** [comment]
> 是这里，没有对应插件就是没有数据了，那有点奇怪了，不清楚和 utools 升级有没有关系，后面看下能不能复现吧

![image](https://github.com/user-attachments/assets/5cc0ec72-7792-4a4a-b0cd-a9bab9290416)

有的不过怎么删😭

**Comment by huankong233** [comment]
> > 是这里，没有对应插件就是没有数据了，那有点奇怪了，不清楚和 utools 升级有没有关系，后面看下能不能复现吧
> 
> ![image](https://private-user-images.githubusercontent.com/49610758/363471431-5cc0ec72-7792-4a4a-b0cd-a9bab9290416.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzczMjYsIm5iZiI6MTcyNTE3NzAyNiwicGF0aCI6Ii80OTYxMDc1OC8zNjM0NzE0MzEtNWNjMGVjNzItNzc5Mi00YTRhLWIwY2QtYTliYWI5MjkwNDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA3NTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZjE3YjY3ZTg3Y2EzMWU5YzY0YzBiNDJiM2FkZmM4NmI1OTNhYzkwNTI0NjBiNGEyMDQ1ZDkwODRhNmM4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZE2yKsoSHsrWed05KVyDMfwgJYHyM8DC1oXS9TUxnmQ)
> 
> 有的不过怎么删😭

卸载了确实数据还在，我研究一下怎么删

**Comment by huankong233** [comment]
> > > 是这里，没有对应插件就是没有数据了，那有点奇怪了，不清楚和 utools 升级有没有关系，后面看下能不能复现吧
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/49610758/363471431-5cc0ec72-7792-4a4a-b0cd-a9bab9290416.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzczMjYsIm5iZiI6MTcyNTE3NzAyNiwicGF0aCI6Ii80OTYxMDc1OC8zNjM0NzE0MzEtNWNjMGVjNzItNzc5Mi00YTRhLWIwY2QtYTliYWI5MjkwNDE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA3NTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlZjE3YjY3ZTg3Y2EzMWU5YzY0YzBiNDJiM2FkZmM4NmI1OTNhYzkwNTI0NjBiNGEyMDQ1ZDkwODRhNmM4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZE2yKsoSHsrWed05KVyDMfwgJYHyM8DC1oXS9TUxnmQ)
> > 有的不过怎么删😭
> 
> 卸载了确实数据还在，我研究一下怎么删

貌似清除缓存也不行，我试了一下，重装了 `utols` 然后数据里已经没有插件的信息了，然后重新安装上之后还是会报一样的错

**Comment by mohuishou** [comment]
周一我看下升级一下工具版本到时候发你试一下吧

**Comment by huankong233** [comment]
> 周一我看下升级一下工具版本到时候发你试一下吧

好的

**Comment by huankong233** [comment]
> [vscode-3.6.0.zip](https://github.com/user-attachments/files/16836304/vscode-3.6.0.zip)
> 
> 可以解压之后拖到 utools 输入框安装试试

貌似还是不行
![image](https://github.com/user-attachments/assets/1ec7aa01-8cb3-44f9-8ba9-90c290ca1b1b)

**Comment by mohuishou** [comment]
这个电脑能访问网络么？有人反馈一样的问题说是没有网络会出现

utools 版本是什么？看上去可能和 utools 有关系

**Comment by huankong233** [comment]
> 这个电脑能访问网络么？有人反馈一样的问题说是没有网络会出现
> 
> utools 版本是什么？看上去可能和 utools 有关系

可以的，谷歌github都没问题

**Comment by huankong233** [comment]
> 这个电脑能访问网络么？有人反馈一样的问题说是没有网络会出现
> 
> utools 版本是什么？看上去可能和 utools 有关系

v5.2.1

**Comment by mohuishou** [comment]
我这边也是用的 5.2.1 没有问题，不过可以试试安装老版本的 utools 试试

**Comment by huankong233** [comment]
> 我这边也是用的 5.2.1 没有问题，不过可以试试安装老版本的 utools 试试

好的

**Comment by huankong233** [comment]
> 我这边也是用的 5.2.1 没有问题，不过可以试试安装老版本的 utools 试试

v5.2.0也不行，草了，老电脑倒是没问题，和vsc有关系嘛，这个我怀疑

**Comment by huankong233** [comment]
> > 我这边也是用的 5.2.1 没有问题，不过可以试试安装老版本的 utools 试试
> 
> v5.2.0也不行，草了，老电脑倒是没问题，和vsc有关系嘛，这个我怀疑

![image](https://github.com/user-attachments/assets/daeba241-c903-436e-864e-6a5a7add5437)

**Comment by corvofeng** [comment]
我看了一下代码， 是这里的 `_rev` 需要删掉， 似乎是utools的db创建对象时，`_rev` 的格式校验导致出错了

https://www.u.tools/docs/developer/db.html

```
    let data = itemOld as { _id: string; _rev: string; data: any };
```
https://github.com/mohuishou/utools/blob/98dd8d4b74f5d53a0278a707afd806a8122e88e8/helper/src/config/config.ts#L69

我提个PR吧

**Comment by huankong233** [comment]
> 我看了一下代码， 是这里的 `_rev` 需要删掉， 似乎是utools的db创建对象时，`_rev` 的格式校验导致出错了
> 
> https://www.u.tools/docs/developer/db.html
> 
> ```
>     if (!data) data = { _id: "config", _rev: "", data: {} };
> ```
> 
> https://github.com/mohuishou/utools/blob/98dd8d4b74f5d53a0278a707afd806a8122e88e8/helper/src/config/config.ts#L73
> 
> 我提个PR吧

好像是的，我看不需要rev

**Comment by corvofeng** [comment]
@mohuishou 你没出错的原因是因为db中已经有值了。我也是换了新电脑才出错的

**Comment by mohuishou** [comment]
> @mohuishou 你没出错的原因是因为db中已经有值了。我也是换了新电脑才出错的

👍 我合并后发个版本，应该是 utools 那边更新了 api 导致的

**Comment by huankong233** [comment]
> 已经提交审核，也可以先使用手动打包的版本
> 
> [vscode-3.5.0.zip](https://github.com/user-attachments/files/16901748/vscode-3.5.0.zip)

经过测试，已经可以正常使用了
