### ISSUE TITLE
otp qrcode该如何使用？

### ISSUE THREAD

**Issue by cxgreat2014** [mohuishou/utools#11]
一直没找到这个怎么使用的说明

**Comment by mohuishou** [comment]
otp 搜索名称
opt-add 添加新的两步验证
自动识别二维码添加

**Comment by mohuishou** [comment]
如果有二维码直接复制二维码就可以识别加入了，然后输入 otp 就可以看到所有的两步认证

**Comment by cxgreat2014** [comment]
好的，总算是知道怎么扫描使用二维码了，谢谢大大
