### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Users\xxx\AppData\Roaming\Code\storage.json‘

### ISSUE THREAD

**Issue by zhanglexx** [mohuishou/utools#115]
utools版本：v5.2.1
vsc插件版本：v3.5.3
vscode版本：1.95.2

**Comment by mohuishou** [comment]
utools 输入 `vsc-settings` 可以修改对应配置，不过这个文件配置是很老的版本的 vscode 会用到的了，也可以卸载重装试试

**Comment by zhanglexx** [comment]
> utools 输入 `vsc-settings` 可以修改对应配置，不过这个文件配置是很老的版本的 vscode 会用到的了，也可以卸载重装试试

使用vsc-settings查看，发现是utools的账号同步功能 把其他电脑的配置同步过来 覆盖了本机的db路径，更换路径后已经解决 感谢
