### ISSUE TITLE
iconfont提示 "window.exports未配置"

### ISSUE THREAD

**Issue by fengyun8** [mohuishou/utools#12]
问题： iconfont提示 "window.exports未配置"

![image](https://user-images.githubusercontent.com/8663112/81474670-ab1fca80-9239-11ea-9627-8ea2b1b68494.png)

请问是怎么回事？

**Comment by mohuishou** [comment]
这个插件还没适配新版本

**Comment by mohuishou** [comment]
已修复 https://github.com/mohuishou/utools/releases/tag/v1.11.0
https://github.com/mohuishou/utools/blob/master/CHANGELOG.md#1110-2020-05-10

**Comment by fengyun8** [comment]
thanks
