### ISSUE TITLE
win10下使用无法使用vsc打开项目

### ISSUE THREAD

**Issue by neolin0629** [mohuishou/utools#14]
utool版本 v1.0.6-beta
vscode插件版本  v2.0.3

能正常搜索到历史项目，但是回车后无反应，无法打开项目。
第一次使用是可以打开的，后来不行了，不清楚原因。
path配置正常，终端可以code打开。

使用时截图如下：
![vsc](https://user-images.githubusercontent.com/26494876/82393263-7e10ba80-9a78-11ea-905d-e860637af47c.png)

storage.json如下：
![vsc1](https://user-images.githubusercontent.com/26494876/82393343-a5678780-9a78-11ea-8fa6-2d5a3dd0c165.png)

**Comment by neolin0629** [comment]
把可执行文件(Code.exe)拖动到输入框设置好后，可以打开了。

**Comment by mohuishou** [comment]
> 把可执行文件(Code.exe)拖动到输入框设置好后，可以打开了。

最新版本已修复
