### ISSUE TITLE
vscode历史项目打不开

### ISSUE THREAD

**Issue by ling-love-xin** [mohuishou/utools#16]
在命令行中输入“code" 可以启动vscode，但是使用utools时，无法打开历史，插件版本v2.03，系统win10

**Comment by mohuishou** [comment]
手动吧 code.exe 文件拖到 输入框设置一下试试

**Comment by ling-love-xin** [comment]
也没有问题，我把插件版本降低到了1.53，就没有问题了。


| |
ysling129@126.com
|
|
ysling129@126.com
|
签名由网易邮箱大师定制
在2020年5月21日 11:17，Mo Huishou<notifications@github.com> 写道：

手动吧 code.exe 文件拖到 输入框设置一下试试

**Comment by ling-love-xin** [comment]
感谢您的及时回复
| |
ysling129@126.com
|
|
ysling129@126.com
|
签名由网易邮箱大师定制
在2020年5月21日 11:17，Mo Huishou<notifications@github.com> 写道：

手动吧 code.exe 文件拖到 输入框设置一下试试

**Comment by mohuishou** [comment]
手动设置 `code.exe` 就ok了，但是用默认的 code 命令是不行的对吧？然后你的 vscode 版本是多少呢？

**Comment by mohuishou** [comment]
可以试一下最新版 v2.0.4 修复了这个问题
