### ISSUE TITLE
无法正常打开，建议使用不要直接使用sh，直接使用code执行，将使用系统默认shell

### ISSUE THREAD

**Issue by hxfdarling** [mohuishou/utools#2]
![image](https://user-images.githubusercontent.com/8198794/68933850-7d991d80-07d0-11ea-86fe-0ae75ed845c6.png)

**Comment by mohuishou** [comment]
最新版已经修复这个问题，暂未上线官方插件，请在release中下载
https://github.com/mohuishou/utools/releases/tag/v1.2.2

**Comment by hxfdarling** [comment]
👍

**Comment by hxfdarling** [comment]
你好，有联系方式么？有没有换工作的想法？

**Comment by mohuishou** [comment]
@hxfdarling 不好意思，暂时没有换工作的想法

**Comment by hxfdarling** [comment]
1.3.1 bug由出现了。。。1.2.2正常

**Comment by mohuishou** [comment]
错误信息和上面一样么？我没有复现这个问题

**Comment by hxfdarling** [comment]
一样

2019年11月17日 下午6:14，Mo Huishou <notifications@github.com<mailto:notifications@github.com>> 写道：


错误信息和上面一样么？我没有复现这个问题

**Comment by mohuishou** [comment]
系统信息呢

**Comment by mohuishou** [comment]
我在mac和windows没有复现这个问题，难道是linux?

**Comment by hxfdarling** [comment]
不是，是mac最新系统，等下我再试试重新安装

在 2019年11月17日，20:48，Mo Huishou <notifications@github.com> 写道：

﻿

我在mac和windows没有复现这个问题，难道是linux?

**Comment by mohuishou** [comment]
ok, 源码里面可以看到非windows会使用 `bash` 命令执行
https://github.com/mohuishou/utools/blob/master/vscode/preload.js#L22

**Comment by hxfdarling** [comment]
我重新安装，并重启utools就正常了😂

2019年11月17日 20:52，Mo Huishou <notifications@github.com<mailto:notifications@github.com>> 写道：


ok, 源码里面可以看到非windows会使用 bash 命令执行
https://github.com/mohuishou/utools/blob/master/vscode/preload.js#L22

**Comment by mohuishou** [comment]
大概知道原因了，你应该是最开始在插件商店里面安装的1.2有这个问题，然后1.2.2的时候是重新下载安装的，这个时间段utools没有重启过，安装1.3.1的时候因为没有重启过所以生效的是1.2之前的老版本
