### ISSUE TITLE
vsc更新2.0.5后打不开vscode了

### ISSUE THREAD

**Issue by Dynamith** [mohuishou/utools#20]
直接停在了子输入框上面，我的配置应该没问题，之前一直挺好用

**Comment by mohuishou** [comment]
请提供一下系统版本，vscode 版本，错误信息（如果有的话）

**Comment by Dynamith** [comment]
Windows 10家庭中文版1909
Visual Studio Code 1.46.1(user setup)
没有错误信息，就直接没有反应

**Comment by mohuishou** [comment]
目前无法复现你的错误，用 vsc 时可以打开项目的，你可以尝试以下操作
1. 看一下 `vsc-setting` 返回的信息有没有问题
2. 将 vscode  的可执行文件手动拖到 utools 的输入框，设置为 vscode 执行命令
3. 看一下 utools 的版本信息

**Comment by Dynamith** [comment]
这些我之前都设置过，就是好像在更新2.0.5以后，就不行了，重新设置也不行，我的utools是1.1.1

**Comment by Dynamith** [comment]
我在终端输入code也能打开

**Comment by mohuishou** [comment]
https://github.com/mohuishou/utools/releases/tag/v1.14.4

那你可以试试卸载重装一下，或者用上面的连接按照老版本试试

**Comment by mohuishou** [comment]
好的，我后面看下是不是插件中心的版本有问题，这个报错在打开时间比较长的时候会出现，后面会优化一下

**Comment by Dynamith** [comment]
好的，我记得utools插件中心会置顶最新的插件，但你这次更新的插件没有置顶，会不会跟这个有关

**Comment by mohuishou** [comment]
应该不是，2.0.5 已经更新挺久远的了

**Comment by Dynamith** [comment]
是吗，我前两天还一直用的2.0.4，直到今天才提示更新😂
