### ISSUE TITLE
iconfont插件操作和复制png图片问题和建议

### ISSUE THREAD

**Issue by ourforPP** [mohuishou/utools#24]
插件：iconfont

### 问题2：复制png图片直接粘贴是黑色背景，不能直接使用

![image](https://user-images.githubusercontent.com/45449335/88131853-89b36580-cc10-11ea-87ed-3ba49fb083ec.png)

#### 期望效果：如浏览器端下载的png图片效果一致，透明背景

![image](https://user-images.githubusercontent.com/45449335/88132065-152cf680-cc11-11ea-9892-e210f8fcaaee.png)

**Comment by mohuishou** [comment]
问题1 下个版本加一下

**Comment by mohuishou** [comment]
问题2 无法复现，我这边复制出来的是透明背景，你可以试试复制粘贴到word试试，或者是尝试下载看看

**Comment by ourforPP** [comment]
@mohuishou 
印象笔记、word、visio里，复制粘贴出来都是黑色背景；
下载下来倒是没问题，是透明背景

![image](https://user-images.githubusercontent.com/45449335/88136811-b2415c80-cc1c-11ea-9a71-2fd6671b8130.png)

![image](https://user-images.githubusercontent.com/45449335/88136777-9a69d880-cc1c-11ea-96cb-17b609cc2e56.png)

**Comment by mohuishou** [comment]
不知道和系统有没有关系，晚点我再试一下 windows 的情况

**Comment by ourforPP** [comment]
@mohuishou 
系统：win10专业版，1909

**Comment by mohuishou** [comment]
> @mohuishou
> 系统：win10专业版，1909

找到原因了，windows 的通病，复制图片数据到剪切板的话，不会保留透明度信息，下个版本修复一下

**Comment by ourforPP** [comment]
@mohuishou 赞，功能确实很方便

**Comment by mohuishou** [comment]
请下载最新版本使用
