### ISSUE TITLE
utools-helper 的使用问题

### ISSUE THREAD

**Issue by Nstd** [mohuishou/utools#26]
按照yuque那个项目写的，ts执行`tsc`编译后生成了**dist**目录，把`plugin.json`拖入utools的输入框安装以后，执行插件以后报错：
![image](https://user-images.githubusercontent.com/3004225/88515377-34b38d00-d01e-11ea-99dd-870b996b41d7.png)

项目目录结构
![image](https://user-images.githubusercontent.com/3004225/88515152-d8506d80-d01d-11ea-9dd4-6c0089c5306c.png)

plugin.json
``` json
{
  "pluginName": "SwaggerSearch",
  "version": "0.0.1",
  "description": "搜索Swagger中的api",
  "author": "Nstd",
  "logo": "logo.png",
  "preload": "dist/preload.js",
  "features": [
    {
      "code": "api",
      "explain": "搜索协议",
      "cmds":["api", "apiWeb"]
    },
    {
      "code": "settings",
      "explain": "Swagger搜索设置",
      "cmds": ["Settings"]
    }
  ]
}
```

**Comment by mohuishou** [comment]
看一下 preload.ts 和 preload.js 的内容

**Comment by Nstd** [comment]
preload.ts
``` TypeScript
import { InitPlugins } from "utools-helper";
import { SearchApi } from "./search-api";

InitPlugins([new SearchApi()]);
```

preload.js
``` javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const utools_helper_1 = require("utools-helper");
const search_api_1 = require("./search-api");
utools_helper_1.InitPlugins([new search_api_1.SearchApi()]);

```

**Comment by Nstd** [comment]
@mohuishou 

`utools-helper` 的 `plugin.ts` 文件中有个错误信息，不知道这个有没有影响
![image](https://user-images.githubusercontent.com/3004225/88521909-34b88a80-d028-11ea-9144-2cd0c94d4c7e.png)

**Comment by mohuishou** [comment]
> @mohuishou
> 
> `utools-helper` 的 `plugin.ts` 文件中有个错误信息，不知道这个有没有影响
> ![image](https://user-images.githubusercontent.com/3004225/88521909-34b88a80-d028-11ea-9144-2cd0c94d4c7e.png)

应该和这个没有关系，大概率你这个 `SearchApi` 对象初始化的时候会抛异常导致的，导致 window.exports 这行代码没执行到

**Comment by Nstd** [comment]
> > @mohuishou
> > `utools-helper` 的 `plugin.ts` 文件中有个错误信息，不知道这个有没有影响
> > ![image](https://user-images.githubusercontent.com/3004225/88521909-34b88a80-d028-11ea-9144-2cd0c94d4c7e.png)
> 
> 应该和这个没有关系，大概率你这个 `SearchApi` 对象初始化的时候会抛异常导致的，导致 window.exports 这行代码没执行到

有什么办法能捕捉到这个异常吗？

**Comment by mohuishou** [comment]
我这边已经尝试捕获了，但是由于 utools 的机制问题导致错误还没有弹出插件就退出了，这个后面我看一下能不能输出到一个日志文件里面去，现在临时解决方案，你可以尝试改一下 node_modules 的 dist 里面的文件，尝试加一些 alert 之类的

**Comment by Nstd** [comment]
> 我这边已经尝试捕获了，但是由于 utools 的机制问题导致错误还没有弹出插件就退出了，这个后面我看一下能不能输出到一个日志文件里面去，现在临时解决方案，你可以尝试改一下 node_modules 的 dist 里面的文件，尝试加一些 alert 之类的

写了个test case，发现是少安装了一个库，感谢！

**Comment by Nstd** [comment]
utools没法看到运行日志，真难受。。

**Comment by mohuishou** [comment]
> utools没法看到运行日志，真难受。。

是的，调试起来比较麻烦

**Comment by mohuishou** [comment]
在 `preload.ts` 这么写就可以捕获错误了
```javascript
try {
  InitPlugins([new VSCode(), new CMD(), new Setting(), new Storage()]);
} catch (error) {
  alert(error.stack ? error.stack : error);
}
```

**Comment by Nstd** [comment]
> 在 `preload.ts` 这么写就可以捕获错误了
> 
> ```js
> try {
>   InitPlugins([new VSCode(), new CMD(), new Setting(), new Storage()]);
> } catch (error) {
>   alert(error.stack ? error.stack : error);
> }
> ```

多谢

**Comment by ViktorMachine** [comment]
> 在 `preload.ts` 这么写就可以捕获错误了
> 
> ```js
> try {
>   InitPlugins([new VSCode(), new CMD(), new Setting(), new Storage()]);
> } catch (error) {
>   alert(error.stack ? error.stack : error);
> }
> ```

请问这个CMD是用的那个包啊？

**Comment by mohuishou** [comment]
> > 在 `preload.ts` 这么写就可以捕获错误了
> > ```js
> > try {
> >   InitPlugins([new VSCode(), new CMD(), new Setting(), new Storage()]);
> > } catch (error) {
> >   alert(error.stack ? error.stack : error);
> > }
> > ```
> 
> 请问这个CMD是用的那个包啊？

这个没关系哈，应该是很早之前 vscode 插件代码里面写的
