### ISSUE TITLE
在 Mac 中 Chrome 历史搜索插件用不了

### ISSUE THREAD

**Issue by meteorsh** [mohuishou/utools#29]
把 Profile 放到了输入栏但没什么用
![image](https://user-images.githubusercontent.com/46078304/92094106-ab565e00-ee06-11ea-98dd-fd985e60b6fa.png)

ch xxx 什么都没有显示
![image](https://user-images.githubusercontent.com/46078304/92094207-c32de200-ee06-11ea-9580-5763f2006758.png)

**Comment by mohuishou** [comment]
utools 的问题，不能直接复制文件路径，需要把文件夹拖动到 utools 的主输入框才行，拖动 之后会出现下图的设置页面
![image](https://user-images.githubusercontent.com/15172509/92140603-e88d1100-ee43-11ea-9030-29e65396a3db.png)

**Comment by meteorsh** [comment]
成功了，感谢！
