### ISSUE TITLE
chrome地址不对

### ISSUE THREAD

**Issue by yu-yang2** [mohuishou/utools#3]
Error: Command failed: "/Users/yy/Library/Application Support/uTools/plugins/unsafe-55f3531539e9b74773c7221a13a61393.asar.unpacked/search_darwin" -p="/Users/yy/Library/Application Support/Google/Chrome/Default" -q= -t=/var/folders/r8/2txzxbxn6gd7l4jf00c5sl880000gn/T/
panic: open /Users/yy/Library/Application Support/Google/Chrome/Default/History: no such file or directory

goroutine 1 [running]:
main.checkErr(...)
	/Users/lyle.lai/me/utools/chrome-history/search/main.go:12
main.main()
	/Users/lyle.lai/me/utools/chrome-history/search/main.go:29 +0x52e

```
yydeiMac :: ~/Downloads » ls /Users/yy/Library/Application\ Support/Google/Chrome
App Shim Socket               PepperFlash
Avatars                       Profile 1
BrowserMetrics                RunningChromeVersion
BrowserMetrics-spare.pma      SSLErrorAssistant
CertificateRevocation         Safe Browsing
CertificateTransparency       Safe Browsing Cookies
Consent To Send Stats         Safe Browsing Cookies-journal
Crashpad                      SafetyTips
CrashpadMetrics-active.pma    ShaderCache
FileTypePolicies              SingletonCookie
First Run                     SingletonLock
InterventionPolicyDatabase    SingletonSocket
Local State                   Subresource Filter
MEIPreload                    Webstore Downloads
NativeMessagingHosts          WidevineCdm
OriginTrials                  pnacl
```

**Comment by mohuishou** [comment]
你的chrome文件夹里面没有默认的default profile，晚点我添加一个设置profile的选项

**Comment by mohuishou** [comment]
@yu-yang2 请下载最新 1.3.2 版本，使用 `chs` 设置你的 profile 路径
