### ISSUE TITLE
搜索到打开记录，打开vscode项目报错

### ISSUE THREAD

**Issue by jianhao** [mohuishou/utools#33]
如图：
![image](https://user-images.githubusercontent.com/30502487/96091791-9c31f800-0efc-11eb-99d0-8326bdd564d5.png)

![image](https://user-images.githubusercontent.com/30502487/96091678-7b69a280-0efc-11eb-9167-d1606b17b316.png)

不知道是什么原因

**Comment by jianhao** [comment]
害，原来需要设置vscode可以通过shell打开，操作如下：
1、打开vscode，command + shift + p 打开命令行
2、搜索shell command，选择在PATH中安装‘code’命令
3、随便找个终端，输入 ‘code .' 看下是否能通过vscode打开当前目录
4、返回重试即可

**Comment by mohuishou** [comment]
![image](https://user-images.githubusercontent.com/15172509/96106356-b7f1ca00-0f0d-11eb-8126-94a8c3bc0e9b.png)

**Comment by jianhao** [comment]
就是之前没有用code打开过vscode，所以没太明白那个说明的意思。。。
