### ISSUE TITLE
能不能修改一下做一个 Edge 的搜索历史记录插件？

### ISSUE THREAD

**Issue by caiweihan** [mohuishou/utools#35]
如题，如今很多 Windows 用户使用 Edge 而不是 Chrome，作者能不能开发一个 Edge 的搜索历史记录插件？

**Comment by mohuishou** [comment]
不用修改，是支持的。请查看对应插件的readme有使用说明
--------------原始邮件--------------
发件人："蔡维翰 "<notifications@github.com&gt;;
发送时间：2020年11月1日(星期天) 下午4:42
收件人："mohuishou/utools" <utools@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[mohuishou/utools] 能不能修改一下做一个 Edge 的搜索历史记录插件？ (#35)
-----------------------------------

 

 
如题，如今很多 Windows 用户使用 Edge 而不是 Chrome，作者能不能开发一个 Edge 的搜索历史记录插件？

**Comment by caiweihan** [comment]
> 不用修改，是支持的。请查看对应插件的readme有使用说明 --------------原始邮件-------------- 发件人："蔡维翰 "<notifications@github.com&gt;; 发送时间：2020年11月1日(星期天) 下午4:42 收件人："mohuishou/utools" <utools@noreply.github.com&gt;; 抄送："Subscribed "<subscribed@noreply.github.com&gt;; 主题：[mohuishou/utools] 能不能修改一下做一个 Edge 的搜索历史记录插件？ (#35) ----------------------------------- 如题，如今很多 Windows 用户使用 Edge 而不是 Chrome，作者能不能开发一个 Edge 的搜索历史记录插件？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢，其实你可以将“支持 Edge” 添加到 uTools 的插件描述中，这样更多的人可以看到。
