### ISSUE TITLE
vsc插件使用出错

### ISSUE THREAD

**Issue by evrstr** [mohuishou/utools#36]
![image](https://user-images.githubusercontent.com/38237340/99185776-043b5e80-2787-11eb-9cc2-b529f11ee55a.png)

**Comment by mohuishou** [comment]
- 看一下能不能在命令行使用 `code .` 打开vscode
- 如果不行，在 vscode 上将 code 命名安装一下

**Comment by evrstr** [comment]
> * 看一下能不能在命令行使用 `code .` 打开vscode
> * 如果不行，在 vscode 上将 code 命令安装一下

可以从命令行打开vscode

**Comment by mohuishou** [comment]
执行一下 vsc-setting 看一下返回值，不行的话可以找到 vscode 的安装位置，复制到 utools 的主输入框，设置一下 path

**Comment by evrstr** [comment]
可以了把vscode复制到 utools 的主输入框就行了，谢谢。
