### ISSUE TITLE
Error: ubrowser destroyed

### ISSUE THREAD

**Issue by my-Sakura** [mohuishou/utools#37]
url undefined
装语雀搜索插件验证完停留在验证成功界面，关闭界面以后使用语雀搜索出现以上错误
![image](https://user-images.githubusercontent.com/69021934/100814325-692bcf80-347c-11eb-8500-ca0a05621a6d.png)

**Comment by mohuishou** [comment]
右键点击右边的图标选择完全退出，重试一下，或者可以输入`语雀设置` 手动设置一下  token

**Comment by my-Sakura** [comment]
问题解决了，手动设置了一下 token

**Comment by mohuishou** [comment]
👌 closed
