### ISSUE TITLE
ubuntu20.04 插件安装后，复制路径到utools没有显示设置chrome路径这个选项

### ISSUE THREAD

**Issue by corbettbain** [mohuishou/utools#39]
![DeepinScreenshot_google-chrome_20201224095549](https://user-images.githubusercontent.com/25195955/103050120-77c65c00-45ce-11eb-9d4e-4df93240e91d.png)

**Comment by mohuishou** [comment]
多试两次呢

**Comment by corbettbain** [comment]
> 多试两次呢
不行呀，今天发现有更新，还特意有试了几次，还是不行哦。

**Comment by mohuishou** [comment]
https://github.com/mohuishou/utools/issues/29#issuecomment-686602017
需要拖动，具体看这个回答

**Comment by corbettbain** [comment]
> [＃29（评论）](https://github.com/mohuishou/utools/issues/29#issuecomment-686602017)
> 需要预先，具体看这个回答

可以了，谢谢；
