### ISSUE TITLE
建议增加配置支持搜索chromium内核的所有浏览器

### ISSUE THREAD

**Issue by m1509001** [mohuishou/utools#4]
建议增加配置支持搜索chromium内核的所有浏览器

**Comment by mohuishou** [comment]
理论上是支持的，只需要设置profile路径即可，这个使用 chs 设置

**Comment by mohuishou** [comment]
请查看使用说明，如果无法解决可以再次打开这个 issue， https://github.com/mohuishou/utools/tree/master/chrome-history#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95
