### ISSUE TITLE
突然打不项目了

### ISSUE THREAD

**Issue by whoopsHzh** [mohuishou/utools#43]
![image](https://user-images.githubusercontent.com/32846446/104865564-53646200-5977-11eb-8e60-fc0c56c827d4.png)

**Comment by mohuishou** [comment]
1. 使用 `vsc-setting` 看一下当前可执行文件的位置
2. 手动使用上面的命令看能不能在终端打开项目
3. 如果不行，可以尝试找到 vscode 的安装路径，找到 `Code.exe` 文件，拖入到输入框，然后手动设置为 vscode 的执行命令

**Comment by xxwhca** [comment]
设置完之后，还是没有解决,只有历史项目搜索打不开

**Comment by mohuishou** [comment]
https://github.com/mohuishou/utools/issues/33#issuecomment-708972272

**Comment by chenpenggood** [comment]
1、打开按照项目，找到Code.exe
2、将Code.exe拖到utools输入框，并输入vsc
3、选择 -> 设置为vscode 可执行文件路径，即可

**Comment by mohuishou** [comment]
> 1、打开安装项目，找到Code.exe
> 2、将Code.exe拖到utools输入框，并输入vsc
> 3、选择 -> 设置为vscode 可执行文件路径，即可

👍 这个先 close 掉了
