### ISSUE TITLE
utools-helper createBrowserWindow 和 isDarkColors两个函数的更新

### ISSUE THREAD

**Issue by suxiaoshao** [mohuishou/utools#44]
utools-helper

1. createBrowserWindow
    这个函数添加了第三个参数callback,类型是Function,添加了返回值,类型是number
2. isDarkColors
    添加了这个函数,返回值是boolean

**Comment by mohuishou** [comment]
可以提个 pr 呀

**Comment by mohuishou** [comment]
已支持 https://www.npmjs.com/package/utools-helper/v/1.5.0
