### ISSUE TITLE
vscode plugin in MacOS

### ISSUE THREAD

**Issue by FoundTheWOUT** [mohuishou/utools#46]
提议在mac下用zsh启动:
https://github.com/mohuishou/utools/blob/b9748798ae656fafe0a3d4628617024eda3d0768/plugins/vscode/src/vscode.ts#L58
现在mac默认shell是zsh, 然后关于个人的PATH设置都是在zsh config里, 用bash启动会导致debug的时候找不到PATH.
当然其实也可以自己设置bash的config...

**Comment by mohuishou** [comment]
> 提议在mac下用zsh启动:
> https://github.com/mohuishou/utools/blob/b9748798ae656fafe0a3d4628617024eda3d0768/plugins/vscode/src/vscode.ts#L58
> 
> 
> 现在mac默认shell是zsh, 然后关于个人的PATH设置都是在zsh config里, 用bash启动会导致debug的时候找不到PATH.
> 当然其实也可以自己设置bash的config...

这个后面可以优化一下，修改一下默认值

**Comment by mohuishou** [comment]
最新版已支持，shell 可以使用 `vsc-setting` 修改

**Comment by FoundTheWOUT** [comment]
我发现改了zsh还是不能正确的获得PATH...怎么回事,
我在terminal跑code .能是正常debug的,
但是用插件就会就debug不了了.
![截屏2021-04-05 下午11 17 41](https://user-images.githubusercontent.com/47922588/113590632-78f33480-9665-11eb-9017-b2319f980a3d.png)
![截屏2021-04-05 下午11 17 51](https://user-images.githubusercontent.com/47922588/113590640-7a246180-9665-11eb-9951-2ca2727befea.png)

**Comment by mohuishou** [comment]
你这个 debug 的意思是在 vscode 里面运行 debug 命令？

**Comment by FoundTheWOUT** [comment]
> 你这个 debug 的意思是在 vscode 里面运行 debug 命令？

这个, vscode自带的Run and Debug
![截屏2021-04-05 下午11 25 48](https://user-images.githubusercontent.com/47922588/113591293-4b5abb00-9666-11eb-8e3e-5b94b29ea3ce.png)

**Comment by mohuishou** [comment]
这个要看一下你的环境问题了，按理说这个应该和启动方式关系不大才对

**Comment by FoundTheWOUT** [comment]
用其它插件时无意中想到了一个解决方法.
就是不在node中运行启动脚本, 而是用`osascript`去调用本地terminal然后跑命令.
https://github.com/fofolee/uTools-quickcommand/blob/master/src/preload.js#L396
## 问题原因
在Unix系统中, 不同于Window, 我们一般都是在shell的conf下追加PATH, 比如`.zshrc`中追加node路径, 或者其它包路径
然而当我们用`zsh -l -c`时它会根据其调用者(当前node)路径进行响应, 在utools中的node是一个沙盒, 它的环境仅仅包含了必要的参数, 没有也理应没有办法拿到用户的个人配置(除非添加设置选项), 那么启动后的vscode找不到软件的路径也就理所当然了.
## 解决办法
启用一个terminal进程, 让该进程运行`code`, 这样就能有效的避免环境丢失的问题.
## 示例
https://github.com/FoundTheWOUT/utools/commit/e06e70543ebd621ca2bd3534486306197afd70b1
## 其它问题
- Unix系统中, 如果目录路径带有空格, 启动会失效(路径中空格应改为'\ ', 但我想不到什么好办法)
- `utools.d.ts`中`isMacOs` `isWindows` `isLinux`三个方法应该返回布尔值
