### ISSUE TITLE
MacOS下打开历史项目报错

### ISSUE THREAD

**Issue by Renato-Z** [mohuishou/utools#47]
![image](https://user-images.githubusercontent.com/50518861/112100808-a4473f80-8be0-11eb-8b4f-445b6e2e3044.png)
已经设置了path，code . 可以打开vscode

**Comment by mohuishou** [comment]
试一下在 执行 `bash -l -c "code ."` 能不能打开 vscode

**Comment by Renato-Z** [comment]
这里执行显示bash: code: command not found，应该怎么配置呢

**Comment by mohuishou** [comment]
一般在 vscode 里面执行一下这个就可以了
![image](https://user-images.githubusercontent.com/15172509/112104010-934cfd00-8be5-11eb-880e-ad55d3c22478.png)

**Comment by Renato-Z** [comment]
解决了，多谢了

**Comment by mohuishou** [comment]
这个先 close 了，后面这个命令会考虑做成可选项
