### ISSUE TITLE
今天忽然无法打开历史项目了，输入关键字没有项目显示

### ISSUE THREAD

**Issue by neolin0629** [mohuishou/utools#48]
之前都可以正常运行，在今天升级了vscode后就不行了。
vscode版本：
![image](https://user-images.githubusercontent.com/26494876/113231655-4d232800-92ce-11eb-8295-5a383dbecc02.png)

vsc-setting：
![image](https://user-images.githubusercontent.com/26494876/113231671-5b714400-92ce-11eb-9c6e-5f7db5012be8.png)

storage.json内容：
![image](https://user-images.githubusercontent.com/26494876/113231749-7cd23000-92ce-11eb-8893-50b83b09481b.png)

输入关键字没有项目显示：
![image](https://user-images.githubusercontent.com/26494876/113231791-92475a00-92ce-11eb-8fd3-0696ceec380f.png)

**Comment by SvenZhao** [comment]
+1

**Comment by yanyongyu** [comment]
我也是，阅读源码后发现是因为

https://github.com/mohuishou/utools/blob/b9748798ae656fafe0a3d4628617024eda3d0768/plugins/vscode/src/vscode.ts#L19

导致的

**Comment by mohuishou** [comment]
晚点修复一下

**Comment by mohuishou** [comment]
已修复可以试试 github 上最新的 release 版本

**Comment by mohuishou** [comment]
已修复可以试试 github 上最新的 release 版本
