### ISSUE TITLE
utools插件不能打开搜索

### ISSUE THREAD

**Issue by xcbt9527** [mohuishou/utools#49]
在utools使用vsc进行页面搜索打卡，没有历史项目地址
![image](https://user-images.githubusercontent.com/20396146/113369806-cb4a0200-9394-11eb-98ad-761506148f19.png)

**Comment by mohuishou** [comment]
请下载 github 上的最新版

**Comment by neolin0629** [comment]
下载最新版后报如下错误
![image](https://user-images.githubusercontent.com/26494876/113370093-98ecd480-9395-11eb-9e4c-0337ec2201d6.png)

是在windows上需要设置shell吗？我看了一下，默认是""，但是我这里如下：
![image](https://user-images.githubusercontent.com/26494876/113370137-b02bc200-9395-11eb-8d68-f63057feb90e.png)

且shell不能为空

**Comment by mohuishou** [comment]
windows 应该默认为空才对，你可以暂时设置为 cmd.exe 试一试，我等下改一下

**Comment by mohuishou** [comment]
或者下载最新版试试 https://github.com/mohuishou/utools/releases/tag/v1.23.2
@neolin0629  已经改过了

**Comment by neolin0629** [comment]
我其实改过 cmd /c的，但是还是要报如下错误。。。
![image](https://user-images.githubusercontent.com/26494876/113370936-a99e4a00-9397-11eb-918e-af62c7fc80c2.png)

新版本也是，是我这边设置问题吗？
![image](https://user-images.githubusercontent.com/26494876/113370992-c76baf00-9397-11eb-853f-9f668dd99753.png)

**Comment by lblblong** [comment]
新版可以，完美解决！！

**Comment by lblblong** [comment]
![image](https://user-images.githubusercontent.com/18625523/113371198-5c6ea800-9398-11eb-8679-449ae2442a87.png)
欸，同样问题，显示项目列表的问题可以，打不开项目。。

**Comment by mohuishou** [comment]
等会儿我搞个 windows 虚拟机试试，没有windows没法测试

**Comment by lblblong** [comment]
![image](https://user-images.githubusercontent.com/18625523/113372276-ddc73a00-939a-11eb-9d3d-ff732384d8e6.png)

大佬，你在 windows上拼出来的命令跑不了，多了单引号，去掉就可以了，下面那种可以

**Comment by mohuishou** [comment]
@lblblong @xcbt9527 @neolin0629 可以再试试，已经修复了

**Comment by lblblong** [comment]
新版本还是不可以

**Comment by mohuishou** [comment]
> 新版本还是不可以

我在 windows 上测试过，你贴一下 `vsc-setting` 的配置呢

**Comment by lblblong** [comment]
![image](https://user-images.githubusercontent.com/18625523/113374094-df92fc80-939e-11eb-8cff-9c68b70e279c.png)
shell留空的

**Comment by mohuishou** [comment]
@lblblong 报错呢？

**Comment by mohuishou** [comment]
可以把 `code` 修改为你本地 vscode 的 `exe` 文件路径试试

**Comment by lblblong** [comment]
@mohuishou 无报错，选择项目之后没反应

**Comment by lblblong** [comment]
![image](https://user-images.githubusercontent.com/18625523/113374499-d9515000-939f-11eb-912a-c6b541a75d54.png)

这样改可以了 @mohuishou

**Comment by mohuishou** [comment]
你这个应该是 code 命令没有 path 当中导致的

**Comment by neolin0629** [comment]
> 可以把 `code` 修改为你本地 vscode 的 `exe` 文件路径试试

是的，这样改后就可以了。

我在cmd里直接code是可以打开vscode的，但是如果不修改为exe文件路径确实不能运行。

**Comment by mohuishou** [comment]
> > 可以把 `code` 修改为你本地 vscode 的 `exe` 文件路径试试
> 
> 是的，这样改后就可以了。
> 
> 我在cmd里直接code是可以打开vscode的，但是如果不修改为exe文件路径确实不能运行。

感觉是 windows 的处理有问题，我刚刚试了一下也发现了 `cmd.exe /c "code ."` 就执行不了了，但是直接运行是可以的

**Comment by lblblong** [comment]
> 你这个应该是 code 命令没有 path 当中导致的

code是在我的环境变量里的，直接在cmd或者powershell里输入code都可以打开的

**Comment by mohuishou** [comment]
@lblblong @neolin0629 默认命令应该也可以了，下载一下最新版
https://github.com/mohuishou/utools/releases/download/v1.23.4/vscode-v3.0.3.upx

**Comment by lblblong** [comment]
@mohuishou 可以了！

**Comment by mohuishou** [comment]
先关闭了，有问题可以再次打开
