### ISSUE TITLE
chrome历史记录搜索以后没响应

### ISSUE THREAD

**Issue by yu-yang2** [mohuishou/utools#5]
搜索成功后选中地址回车没有跳转也没有复制地址

**Comment by mohuishou** [comment]
请问系统版本，utools版本，chrome版本是什么呢

**Comment by mohuishou** [comment]
可以看一下是否有设置默认浏览器

**Comment by mohuishou** [comment]
v1.4.2 修复该问题：https://github.com/mohuishou/utools/releases/tag/v1.4.2 安装新版之后记得重启一下 utools， 如果还有问题可以重开这个 issue
