### ISSUE TITLE
4.1号更新之后，就报错zsh的错误了

### ISSUE THREAD

**Issue by xxwhca** [mohuishou/utools#51]
![image](https://user-images.githubusercontent.com/48832741/113377526-1cfb8800-93a7-11eb-88c5-0429b718cd16.png)

**Comment by mohuishou** [comment]
如果是 windows 可以先下载 github 上的最新版，如果是 Mac OS 可以看一下在终端是否能执行 `code .` 打开文件夹

**Comment by xxwhca** [comment]
已解决，mac电脑，重新在vscode中执行了一下code命令

**Comment by mohuishou** [comment]
那先关闭了
