### ISSUE TITLE
双系统问题

### ISSUE THREAD

**Issue by FoundTheWOUT** [mohuishou/utools#52]
emmm，我是双系统使用者，之前vsc都是用的本地配置所以没有问题，现在新版改成了远程配置，我从笔记本换到电脑的时候各种报错。。主要是shell和storage问题，我已经可以设想当我在台式重新配置后回到笔记本的场景:smile:

**Comment by mohuishou** [comment]
新版是有这个问题，我晚点兼容一下

**Comment by mohuishou** [comment]
最新版支持了，可以试试 https://github.com/mohuishou/utools/releases/tag/v1.24.0
