### ISSUE TITLE
离线下载插件在utools可以安装吗

### ISSUE THREAD

**Issue by InstantWindy** [mohuishou/utools#53]
怎么离线下载utools的插件并安装呢

**Comment by mohuishou** [comment]
可以的，下载 release 中的插件，把文件拖进 utools 的输入框就能安装了

**Comment by InstantWindy** [comment]
哪里可以离线下载这些插件呢?谢谢

**Comment by mohuishou** [comment]
https://github.com/mohuishou/utools/releases/tag/v1.24.1

**Comment by InstantWindy** [comment]
其他的插件在哪里可以下载？

**Comment by mohuishou** [comment]
不太清楚，去官方论坛问吧
