### ISSUE TITLE
打开文件报错

### ISSUE THREAD

**Issue by LiDongYang743** [mohuishou/utools#57]
![image](https://user-images.githubusercontent.com/59534637/118213240-1c730880-b4a0-11eb-8d55-c71dd87a5c1a.png)
Error: Command failed: code --folder- uri fl:///d:/workpackges/junxin webProject/baoankaoshi/exa...

**Comment by mohuishou** [comment]
可以自己在本地执行一下上面的命令，看能不能打开

**Comment by LiDongYang743** [comment]
![image](https://user-images.githubusercontent.com/59534637/118234871-87cfd100-b4c6-11eb-84ec-b1b27af30690.png)
code 加上文件夹目录可以使用的

**Comment by mohuishou** [comment]
可以看看 `vsc-setting` 的配置，如果没问题的话，检查一下系统环境变量的 PATH 里面有没有 code 命令

**Comment by LiDongYang743** [comment]
问题解决了，感谢，应该是新安装的vscode需要电脑重启，把code加入到path中
