### ISSUE TITLE
希望 vscode 历史项目插件能置顶项目

### ISSUE THREAD

**Issue by Lantern-r** [mohuishou/utools#59]
希望 vscode 历史项目插件能置顶项目。

**Comment by mohuishou** [comment]
好主意，这个有空加一下，最近有点忙

**Comment by Lantern-r** [comment]
感谢！Thanks♪(･ω･)ﾉ

> 好主意，这个有空加一下，最近有点忙

**Comment by mohuishou** [comment]
https://github.com/mohuishou/utools/commit/20e243d595647bc771613aa7f1d0726dc98c521c

已支持，待新版 utools 发布后即可看到
