### ISSUE TITLE
macOS下vscode插件无法使用

### ISSUE THREAD

**Issue by iblogc** [mohuishou/utools#6]
输入vsc > 回车，之后输入框就无法输入内容搜索项目，path配置正常，code . 能打开vscode

**Comment by mohuishou** [comment]
没有报错信息么？你当前的utools 版本，插件版本？

**Comment by iblogc** [comment]
插件版本：1.3.1

**Comment by iblogc** [comment]
utools版本:：0.8.7-beta
插件版本：1.3.1
没有报错

**Comment by sdir** [comment]
![image](https://user-images.githubusercontent.com/13232593/69770845-87098900-11c5-11ea-80c6-82fdd291aad9.png)
utools版本:：0.8.7-beta
插件版本：1.3.3
windows10 专业版，同样的问题，光标没有聚焦，也不能输入

**Comment by mohuishou** [comment]
@iblogc @sdir 可以试一下最新的 1.3.4 看一下运行的时候有没有报错，如果还是有问题的话，可能需要 utools 官方看一下是什么问题了

**Comment by sdir** [comment]
> @iblogc @sdir 可以试一下最新的 1.3.4 看一下运行的时候有没有报错，如果还是有问题的话，可能需要 utools 官方看一下是什么问题了 https://github.com/mohuishou/utools/releases/tag/v1.3.4

![image](https://user-images.githubusercontent.com/13232593/69778721-55ea8200-11e0-11ea-84b1-8dd038418f53.png)

**Comment by mohuishou** [comment]
@sdir `%APPDATA%\Code` windows 进入这个文件夹看一下是否存在 `storage.json` 这个文件，如果存在，如果没有敏感信息可以分享一下内容，或者截图看一下

**Comment by sdir** [comment]
> @sdir `%APPDATA%\Code` windows 进入这个文件夹看一下是否存在 `storage.json` 这个文件，如果存在，如果没有敏感信息可以分享一下内容，或者截图看一下
```json
"workspaces3": [
            {
                "id": "123456",
                "configURIPath": "file:///d%3A/a.code-workspace"
            },
            "file:///d%3A/workspace/b",
            "file:///d%3A/workspace/c"
]
```
对于保存为工作区的，不是路径还有ID。所以使用 file.indexOf("vscode-remote") 会报错

**Comment by mohuishou** [comment]
@sdir 你的vscode版本是多少呢

**Comment by mohuishou** [comment]
@sdir 了解了，我稍后修复一下

**Comment by mohuishou** [comment]
@sdir @iblogc 请尝试最新 v1.3.5 https://github.com/mohuishou/utools/releases/tag/v1.3.5

**Comment by sdir** [comment]
> @sdir @iblogc 请尝试最新 v1.3.5 https://github.com/mohuishou/utools/releases/tag/v1.3.5
> 支持了工作区

有个小小建议：
* 是否可以考虑把工作区的那个后缀code-workspace 去掉显示

**Comment by iblogc** [comment]
> @sdir @iblogc 请尝试最新 v1.3.5 https://github.com/mohuishou/utools/releases/tag/v1.3.5
> 支持了工作区

Windows 10 里可使用，明天我试下macOS下的

**Comment by mohuishou** [comment]
> > @sdir @iblogc 请尝试最新 v1.3.5 https://github.com/mohuishou/utools/releases/tag/v1.3.5
> > 支持了工作区
> 
> 有个小小建议：
> 
> * 是否可以考虑把工作区的那个后缀code-workspace 去掉显示

这是为了标识他是工作区，不然就区分不出来了

**Comment by mohuishou** [comment]
这个问题标记修复了，如果还有问题的话可以重新打开
