### ISSUE TITLE
iconfont setting  ‘是否精选 / 图标类型 ’ 不能选回  '所有图标 / 全部'，提示必填项不能为空

### ISSUE THREAD

**Issue by 912187345** [mohuishou/utools#62]
系统:window7
uTools版本:1.3.5
插件版本:2.4.0

**Comment by mohuishou** [comment]
新版已经修复了等 utools 2.0 发布后就能更新了

**Comment by mohuishou** [comment]
https://github.com/mohuishou/utools/releases/tag/v1.25.0
急用的话，可以先下载这里的
