### ISSUE TITLE
语雀搜索找不到了。

### ISSUE THREAD

**Issue by gclm** [mohuishou/utools#66]
![image](https://user-images.githubusercontent.com/27618687/128303796-876ec976-795b-48a8-a706-8bff6be12b96.png)
![image](https://user-images.githubusercontent.com/27618687/128303833-d0e70665-e981-436f-ba90-4cdede121136.png)

**Comment by mohuishou** [comment]
utools 2.0 了，官方可能忘记迁移了，我抽个时间重新上架一下

**Comment by gclm** [comment]
好的。
