### ISSUE TITLE
VSCode插件无法输入文本

### ISSUE THREAD

**Issue by liukch** [mohuishou/utools#7]
输入 vsc 激活插件后, 光标没有落在输入框里
手动将光标放到输入框之后无法输入文本

**Comment by mohuishou** [comment]
请使用最新版 https://github.com/mohuishou/utools/releases/tag/v1.3.5

**Comment by liukch** [comment]
目前 VSC 插件为1.3.5版本, 输入 vsc 命令激活后出现错误提示
![image](https://user-images.githubusercontent.com/35715689/70109797-fb41a200-1687-11ea-89de-4fcef006933e.png)

**Comment by mohuishou** [comment]
@liukch %APPDATA%\Code windows 进入这个文件夹看一下是否存在 storage.json 这个文件，如果存在，如果没有敏感信息可以分享一下内容，或者截图看一下

**Comment by liukch** [comment]
@mohuishou  
%APPDATA% 下仅存在 Code 文件夹, 其中存在 storage.json,  
没有 Code windows 文件夹,
storage.json 比较大, 没有办法都贴出来, 不知道哪个字段可以帮你排查问题呢? 我可以尽量贴出来。

**Comment by mohuishou** [comment]
@liukch 取得这个字段
```json
"workspaces3": [
            {
                "id": "123456",
                "configURIPath": "file:///d%3A/a.code-workspace"
            },
            "file:///d%3A/workspace/b",
            "file:///d%3A/workspace/c"
]
```

**Comment by liukch** [comment]
@mohuishou 
不存在这个字段
仅有一个类似的  

``` json
    "openedPathsList": {
        "workspaces2": [
            "file:///c%3A/Users/xxx",
        ],
        "files2": [
            "file:///c%3A/Users/xxx"
        ]
    },
```

**Comment by mohuishou** [comment]
你的vscode版本是多少？

**Comment by mohuishou** [comment]
@liukch 原因应该就是不存在这个字段的问题

**Comment by liukch** [comment]
@mohuishou 
版本比较老了
是1.28.0
我升级之后试一下

**Comment by mohuishou** [comment]
好的

**Comment by liukch** [comment]
升级到 1.40.2 问题解决了

**Comment by mohuishou** [comment]
ok，那这个问题关闭了
