### ISSUE TITLE
Bug: vscode remote open failed

### ISSUE THREAD

**Issue by yanyongyu** [mohuishou/utools#70]
vscode在打开远程项目时执行的命令并不一致，实际是把storage里存储的 `vscode-remote://ssh-remote+user@host/path/to/project` URI 拆成两半并且 option 为 `--remote`

打开远程项目：`code --remote ssh-remote+user@host /path/to/project`

**Comment by mohuishou** [comment]
你的 vscode 版本和平台？我这边用着没有问题

**Comment by yanyongyu** [comment]
vscode 1.62.3 x86-64 linux

**Comment by yanyongyu** [comment]
使用folder-uri打开remote项目表现为：成功连接远程主机，但并未打开任何文件夹、workspace

**Comment by yanyongyu** [comment]
尝试了一下，只有在打开远程工作区workspace的时候会显示无打开的文件夹，folder没有问题

**Comment by yanyongyu** [comment]
查看vscode源码、测试代码发现 workspace 应该使用 `--file-uri` option 打开

![image](https://user-images.githubusercontent.com/42488585/143006054-864939cc-05a3-4543-a340-ba0fdde25e79.png)

**Comment by yanyongyu** [comment]
判断地址是文件还是文件夹可能有点困难，要不可以判断以 `.code-workspace` 结尾的工作区文件使用file-uri打开？

**Comment by mohuishou** [comment]
https://github.com/mohuishou/utools/commit/fb3338fc2a46233ed927b7d0c62367a111a2d345
done
