### ISSUE TITLE
vscode 1.64.0 的 json 文件修改了，导致无法查到历史了

### ISSUE THREAD

**Issue by MicePilot** [mohuishou/utools#74]
1.64.0 的 json 文件
![image](https://user-images.githubusercontent.com/13869645/152739222-6ecb18c6-3501-4b40-9954-682a0de280cc.png)
低版本的 json 文件
![image](https://user-images.githubusercontent.com/13869645/152739296-d2fb2fee-4fee-4ddc-9ba8-28f8d3341ebe.png)
看起来 1.64.0 的 json 组织形式中 openedPathsList 被删除了，数据改为保存到 submenuitem.32 下边的 submenu 里了，望修复一波

**Comment by Attiv** [comment]
+1

**Comment by mohuishou** [comment]
今天晚点支持一下哈

**Comment by MicePilot** [comment]
> 今天晚点支持一下哈

我摸索着开发完了，本地测试没问题，不知道怎么提交，在 vscode.ts 中 getfiles 中加了这么一段。没搞过 js，照葫芦画瓢整了一个，看看有没有啥帮助吧
`let targetData = data.lastKnownMenubarData.menus.File.items
    for (const item in targetData) {
      if (targetData[item].id === 'submenuitem.32') {
        let realData = targetData[item].submenu.items
        for (const recent in realData) {
          if (realData[recent].id === 'openRecentFolder') {
            if (realData[recent].uri.hasOwnProperty('external')) {
              files = files.concat(realData[recent].uri.external);
            } else {
              files = files.concat(realData[recent].uri.path);
            }
          }
        }
      }
    }`
![image](https://user-images.githubusercontent.com/13869645/152761891-7d046cd5-12e9-400a-90e0-a731a418c521.png)

**Comment by mohuishou** [comment]
已修复
