### ISSUE TITLE
vscode 插件 3.4.1 还是没有历史记录

### ISSUE THREAD

**Issue by virzs** [mohuishou/utools#75]
## vscode 信息

版本: 1.64.0 (user setup)
提交: 5554b12acf27056905806867f251c859323ff7e9
日期: 2022-02-03T04:22:20.678Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

## 问题

![image](https://user-images.githubusercontent.com/44538687/152924891-3e76e3c5-f73e-447d-8830-8172092796ab.png)

并且如图所示报错

这是我的 storage.json 文件

``` json
{
    "telemetry.machineId": "xxx",
    "theme": "vs-dark",
    "themeBackground": "#23272e",
    "windowsState": {
        "lastActiveWindow": {
            "folder": "xxx",
            "backupPath": "xxx",
            "uiState": {
                "mode": 0,
                "x": 448,
                "y": 156,
                "width": 1024,
                "height": 768
            }
        },
        "openedWindows": [
            {
                "workspaceIdentifier": {
                    "id": "xxx",
                    "configURIPath": "xxx"
                },
                "backupPath": "xxx",
                "uiState": {
                    "mode": 0,
                    "x": 200,
                    "y": 0,
                    "width": 1720,
                    "height": 1032
                }
            },
            {
                "folder": "xxx",
                "backupPath": "xxx",
                "uiState": {
                    "mode": 0,
                    "x": 448,
                    "y": 156,
                    "width": 1024,
                    "height": 768
                }
            }
        ]
    },
    "pickerWorkingDir": "xxx",
    "quit.from.restart": true,
    "windowSplash": {
        "baseTheme": "vs-dark",
        "colorInfo": {
            "foreground": "#cccccc",
            "background": "#23272e",
            "editorBackground": "#23272e",
            "titleBarBackground": "#23272e",
            "activityBarBackground": "#23272e",
            "sideBarBackground": "#1e2227",
            "statusBarBackground": "#1e2227",
            "statusBarNoFolderBackground": "#1e2227"
        },
        "layoutInfo": {
            "sideBarSide": "left",
            "editorPartMinWidth": 220,
            "titleBarHeight": 30,
            "activityBarWidth": 48,
            "sideBarWidth": 0,
            "statusBarHeight": 22,
            "windowBorder": false
        }
    }
}
```

文件中并没有历史记录数据，我不清楚是什么原因，但 vscode 打开最近文件里是有纪录的

**Comment by mohuishou** [comment]
看下 vsc setting 的设置，是不是文件路径不对

**Comment by virzs** [comment]
> 看下 vsc setting 的设置，是不是文件路径不对

文件路径一直没有变过，VS Code更新后插件就不能用了，我也全局搜索过 VS Code 相关的只有这一个 storage.json 文件

**Comment by mohuishou** [comment]
重启一下试试呢

**Comment by mohuishou** [comment]
完全重启进程。保险一点，重启一下电脑，这个是直接没有历史数据了

**Comment by virzs** [comment]
> 完全重启进程。保险一点，重启一下电脑，这个是直接没有历史数据了

![image](https://user-images.githubusercontent.com/44538687/152932567-9e66a6bb-c558-45d4-a86b-800a28ad1f74.png)

我重启过了，还是没有，但软件里能看到

**Comment by mohuishou** [comment]
我晚点看能不能测试一下，这个和 mac 的好像不一样

**Comment by virzs** [comment]
> 我晚点看能不能测试一下，这个和 mac 的好像不一样

好的，辛苦了，我也在尝试找到这些数据，如果有新发现的话，再回复

**Comment by mohuishou** [comment]
已经修复了，在等审核了哈，着急可以直接用这个
[vscode-3.4.3.zip](https://github.com/mohuishou/utools/files/8028619/vscode-3.4.3.zip)

**Comment by virzs** [comment]
> 我晚点看能不能测试一下，这个和 mac 的好像不一样

![image](https://user-images.githubusercontent.com/44538687/153103235-729b0f0f-4396-4083-8fb2-b140b9bf66fd.png)

我发现另一款插件 
![image](https://user-images.githubusercontent.com/44538687/153103286-c2cad2ef-081d-4e87-bbf4-0f9ffb799493.png)
已经支持最新的 vscode 了
但这个插件对我来说很多功能用不到，且体验做的不够好，既然它已经支持了，我觉得可以参考下它的解决方法

**Comment by mohuishou** [comment]
方案是一样的，我和这个作者有交流过

**Comment by virzs** [comment]
> 已经修复了，在等审核了哈，着急可以直接用这个 [vscode-3.4.3.zip](https://github.com/mohuishou/utools/files/8028619/vscode-3.4.3.zip)

太好了，那我就等待更新吧
