### ISSUE TITLE
vscode 更新版本后，vsc历史浏览不能用了

### ISSUE THREAD

**Issue by neolin0629** [mohuishou/utools#76]
vscode版本如下：
![image](https://user-images.githubusercontent.com/26494876/152925530-1eab6d4e-a4c1-4b57-b073-2dd28db9ae44.png)

出错提示如下：
![image](https://user-images.githubusercontent.com/26494876/152925549-1d73fa55-3e02-46c3-9f85-9e6250d9e918.png)

麻烦帮忙看一下，谢谢啦。

**Comment by mohuishou** [comment]
发一下 storage.json

**Comment by neolin0629** [comment]
{
    "telemetry.machineId": "7d8e2ccab3c8179f4ccfd67af3df9900458460a2184f0f61d9364e8614cf27b2",
    "theme": "vs-dark",
    "themeBackground": "#1e1e1e",
    "windowSplash": {
        "baseTheme": "vs-dark",
        "colorInfo": {
            "foreground": "#cccccc",
            "background": "#1e1e1e",
            "editorBackground": "#1e1e1e",
            "titleBarBackground": "#3c3c3c",
            "activityBarBackground": "#333333",
            "sideBarBackground": "#252526",
            "statusBarBackground": "#007acc",
            "statusBarNoFolderBackground": "#68217a"
        },
        "layoutInfo": {
            "sideBarSide": "left",
            "editorPartMinWidth": 220,
            "titleBarHeight": 30,
            "activityBarWidth": 48,
            "sideBarWidth": 300,
            "statusBarHeight": 22,
            "windowBorder": false
        }
    },
    "windowsState": {
        "lastActiveWindow": {
            "folder": "file:///e%3A/project/etl",
            "backupPath": "C:\\Users\\lnonl\\AppData\\Roaming\\Code\\Backups\\05dcbb7e5182296d1cb2f1259680a86f",
            "uiState": {
                "mode": 0,
                "x": 2452,
                "y": 275,
                "width": 1024,
                "height": 768
            }
        },
        "openedWindows": [
            {
                "folder": "file:///e%3A/project/etl",
                "backupPath": "C:\\Users\\lnonl\\AppData\\Roaming\\Code\\Backups\\05dcbb7e5182296d1cb2f1259680a86f",
                "uiState": {
                    "mode": 0,
                    "x": 2452,
                    "y": 275,
                    "width": 1024,
                    "height": 768
                }
            },
            {
                "folder": "vscode-remote://ssh-remote%2B10.25.1.49/home/linnan/project/dailywork",
                "backupPath": "C:\\Users\\lnonl\\AppData\\Roaming\\Code\\Backups\\867b1a5303bdf67e077dc2b4cd69ff21",
                "remoteAuthority": "ssh-remote+10.25.1.49",
                "uiState": {
                    "mode": 0,
                    "x": 448,
                    "y": 216,
                    "width": 1024,
                    "height": 768
                }
            }
        ]
    }
}

**Comment by mohuishou** [comment]
看了一下和 #75 一模一样哈，我们在同一个 issue 查看
