### ISSUE TITLE
vscode历史项目搜索存在的问题

### ISSUE THREAD

**Issue by hellojer** [mohuishou/utools#8]
我使用的是vscode官方便携版，目录已经添加到环境变量，命令行工具可以使用code打开目录并且使用正常，但是使用vscode历史搜索插件打开项目的时候，不到5分钟就会自动关闭，请问是不是bug？

![](http://img01.kumiao.net/2020/20200203091926.png)

**Comment by mohuishou** [comment]
这个问题目前没有复现，暂时先挂起

**Comment by carpcai** [comment]
我是macos 10.15.3 ,

**Comment by mohuishou** [comment]
> 我是macos 10.15.3 ,用code . 能打开项目， 当时vscode 打开历史项目时，点回车没反应

请回复一下插件版本，vscode 版本

**Comment by carpcai** [comment]
版本: 1.43.1
提交: fe22a9645b44368865c0ba92e2fb881ff1afce94
日期: 2020-03-18T07:01:41.240Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by mohuishou** [comment]
> VSCODE版本，
> 版本: 1.43.1
> 提交: fe22a9645b44368865c0ba92e2fb881ff1afce94
> 日期: 2020-03-18T07:01:41.240Z
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Darwin x64 19.3.0
> 
> 插件版本：V1.5.1
> utools版本：0.8.9 beta

是否手动设置过 code 执行命令 、 storage.json 路径，可以通过 `vsc-setting` 查看相关路径

**Comment by carpcai** [comment]
嗯嗯，好吧，我在bash和zsh都在.profile里配置了code的path路径，在命令行都能启动。
使用vsc时，也有显示出历史项目，所以storage.json这一步应该是没问题的。
就选中历史项目之后，没有任何反应。 如果需要视频协助重现的话，可加qq：563998753

**Comment by carpcai** [comment]
![image](https://user-images.githubusercontent.com/17467462/77222677-58f2ef00-6b90-11ea-878f-9fb949bf0320.png)
![image](https://user-images.githubusercontent.com/17467462/77222686-6d36ec00-6b90-11ea-8101-bb04e850e8e1.png)

**Comment by mohuishou** [comment]
> 嗯嗯，好吧，我在bash和zsh都在.profile里配置了code的path路径，在命令行都能启动。
> 使用vsc时，也有显示出历史项目，所以storage.json这一步应该是没问题的。
> 就选中历史项目之后，没有任何反应。 如果需要视频协助重现的话，可加qq：563998753

可以尝试在 vscode 中执行一下下面这个操作
![image](https://user-images.githubusercontent.com/15172509/77222717-a40d0200-6b90-11ea-8988-164fc33e195d.png)

**Comment by mohuishou** [comment]
执行 `vsc-setting`  查看显示的 vscode path 路径

**Comment by carpcai** [comment]
成功了，非常感谢大神，是在vscode里安装path的问题，我之前是改.profile的

**Comment by mohuishou** [comment]
> 成功了，非常感谢大神，是在vscode里安装path的问题，我之前是改.profile的

👌因为插件里面执行的bash读取的是系统的配置，你手动改的那个一般只有terminal启动的时候加载
