### ISSUE TITLE
vscode插件关于VS Code Insiders的兼容问题

### ISSUE THREAD

**Issue by bykenx** [mohuishou/utools#9]
由于*VS Code Insiders*在Windows下的默认路径为`C:\Users\xxx\AppData\Roaming\Code - Insiders\storage.json`，而非`C:\Users\xxx\AppData\Roaming\Code\storage.json`导致打开插件时报错

**Comment by scrollbar-ww** [comment]
same problem in mac os

**Comment by mohuishou** [comment]
https://github.com/mohuishou/utools/releases/tag/v1.5.0

**Comment by mohuishou** [comment]
已支持自定义设置storage.json、可执行文件路径

**Comment by LancelotLewis** [comment]
![image](https://user-images.githubusercontent.com/8749615/82005551-37961700-9698-11ea-9cde-4d362b5e2ae6.png)
@mohuishou  这个匹配规则匹配不了 "Code - Insiders.exe" 文件，可以把正则表达式改改

**Comment by mohuishou** [comment]
> ![image](https://user-images.githubusercontent.com/8749615/82005551-37961700-9698-11ea-9cde-4d362b5e2ae6.png)
> @mohuishou 这个匹配规则匹配不了 "Code - Insiders.exe" 文件，可以把正则表达式改改

已修复

**Comment by LancelotLewis** [comment]
> > ![image](https://user-images.githubusercontent.com/8749615/82005551-37961700-9698-11ea-9cde-4d362b5e2ae6.png)
> > @mohuishou 这个匹配规则匹配不了 "Code - Insiders.exe" 文件，可以把正则表达式改改
> 
> 已修复

试了好几次，都是失败，不知道为啥
![mark](http://static.paddings.cn/blog/20200517/Ehg6XSBX8f6p.png?imageslim)

**Comment by mohuishou** [comment]
> > > ![image](https://user-images.githubusercontent.com/8749615/82005551-37961700-9698-11ea-9cde-4d362b5e2ae6.png)
> > > @mohuishou 这个匹配规则匹配不了 "Code - Insiders.exe" 文件，可以把正则表达式改改
> > 
> > 
> > 已修复
> 
> 试了好几次，都是失败，不知道为啥
> ![mark](https://camo.githubusercontent.com/141db35aa8679c8630b383ec522998af1a80845a/687474703a2f2f7374617469632e70616464696e67732e636e2f626c6f672f32303230303531372f4568673658534258386636702e706e673f696d616765736c696d)

有个bug 已修复 https://github.com/mohuishou/utools/releases/latest

**Comment by LancelotLewis** [comment]
@mohuishou 能设置成功了，也能够打开了。就是vscode-insider会被强制关闭
![image](https://user-images.githubusercontent.com/8749615/82149100-df723700-9888-11ea-89a6-4493cab81aa7.png)

**Comment by mohuishou** [comment]
> @mohuishou 能设置成功了，也能够打开了。就是vscode-insider会被强制关闭
> ![image](https://user-images.githubusercontent.com/8749615/82149100-df723700-9888-11ea-89a6-4493cab81aa7.png)

这个好像和新版 utools 有关系，可以观察一下看是不是必现我使用稳定版的 vscode 没有这个问题

**Comment by mohuishou** [comment]
> @mohuishou 能设置成功了，也能够打开了。就是vscode-insider会被强制关闭
> ![image](https://user-images.githubusercontent.com/8749615/82149100-df723700-9888-11ea-89a6-4493cab81aa7.png)

可以看一下最新版，尝试做了兼容
https://github.com/mohuishou/utools/releases/latest

**Comment by LancelotLewis** [comment]
@mohuishou 新版的是可以了。
前两天在试2.02版出错的情况，发现要是本身已经打开了一个 vscode，之后再用 vsc 打开一个就不会出错；如果本身没有打开 vscode，使用 vsc 打开项目就是之前那个错误
