### ISSUE TITLE
Bug: 路径包含`\`无法打开项目

### ISSUE THREAD

**Issue by yanyongyu** [mohuishou/utools#93]
System: Linux

由于AD帐号名是 `domain\user` 的格式。当项目路径包含 `\` 时，无法正确打开项目。

路径示例：

```json
{
  "folderUri": "file:///media/domain%5Cusername/Projects/xxx"
}
```

**Comment by mohuishou** [comment]
本地使用 code 命令可以打开么，这个我无法进行复现，或者使用 code 命令怎么样可以打开

**Comment by yanyongyu** [comment]
测试用 `code --folder-uri "file:///media/domain%5Cusername/Projects/xxx"`, `code --folder-uri "file:///media/domain\\username/Projects/xxx"`可以打开，但插件不行，也许是url encode或者`\`转义的问题

**Comment by mohuishou** [comment]
修复了，3.5.1 插件审核后发布就可以用了
