### ISSUE TITLE
vscode项目搜索报错

### ISSUE THREAD

**Issue by yefengwu** [mohuishou/utools#95]
vsc-settings我已经设置为其他路径，也可以正常工作，但是每次打开之后都会置顶显示这条信息？？
![image](https://user-images.githubusercontent.com/45461486/208836300-8bfa2895-c6cf-4f41-9ab6-9079fdddde53.png)

**Comment by mohuishou** [comment]
可以看下 vsc-settings 的值是什么哈

**Comment by yefengwu** [comment]
![image](https://user-images.githubusercontent.com/45461486/209649244-d4126eef-4aac-48e9-9be6-5c64254445cd.png)
可以正常工作，但是每次都会显示这条信息。

**Comment by yefengwu** [comment]
示例：
![image](https://user-images.githubusercontent.com/45461486/209649366-108339e3-9be2-43fd-a75a-b3ae891a9efc.png)

**Comment by mohuishou** [comment]
可能是个 bug 哈，我晚点看下

**Comment by mohuishou** [comment]
这不是一个 bug 哈，是因为你把这个结果置顶了，用 `ctrl + enter` 即可取消置顶哈

**Comment by yefengwu** [comment]
谢谢，已解决。
